# spring.application.name=thecentralhotel
# server.port=8080

# springdoc.api-docs.enabled=true
# springdoc.swagger-ui.enabled=true

# # for console 
# spring.jpa.properties.hibernate.format_sql=true



# # spring.datasource.url=jdbc:mysql://localhost:3306/thecentralhotel
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER_NAME}
# spring.datasource.password=${DB_PASSWORD}

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# cloudinary.cloud-name=${CLOUDINARY_HOST_NAME}
# cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# cloudinary.api-key=${CLOUDINARY_API_KEY}

# # Let’s define the maximum file size that can be uploaded 
# spring.servlet.multipart.max-file-size=500KB
# spring.servlet.multipart.max-request-size=500KB
spring:
  application:
    name: thecentralhotel
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc: 
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB       
server:
  port: ${SERVER_PORT}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
cloudinary:
  cloud-name: ${CLOUDINARY_HOST_NAME}
  api-secret: ${CLOUDINARY_API_SECRET}
  api-key: ${CLOUDINARY_API_KEY}
  
